export const clientsData = [
  {
    id: 1,
    firstName: 'Kristin',
    lastName: 'Watson',
    email: 'kristin.watson@example.com',
    phoneNumber: '555-1234',
    address: '123 Main St, Cityville, CA 12345',
    companyName: 'Tech',
    status: 'Active',
  },
  {
    id: 2,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phoneNumber: '555-5678',
    address: '456 Oak St, Townsville, NY 67890',
    companyName: 'Widgets Inc.',
    status: 'Inactive',
  },
  {
    id: 3,
    firstName: 'Emily',
    lastName: 'Johnson',
    email: 'emily.johnson@example.com',
    phoneNumber: '555-8765',
    address: '789 Elm St, Villagetown, TX 54321',
    companyName: 'Innovate Corp.',
    status: 'Active',
  },
  {
    id: 4,
    firstName: 'Michael',
    lastName: 'Smith',
    email: 'michael.smith@example.com',
    phoneNumber: '555-4321',
    address: '987 Birch St, Hamletville, CA 67890',
    companyName: 'Tech Solutions',
    status: 'Inactive',
  },
  {
    id: 5,
    firstName: 'Sarah',
    lastName: 'Miller',
    email: 'sarah.miller@example.com',
    phoneNumber: '555-7890',
    address: '654 Pine St, Villagetown, NY 12345',
    companyName: 'Data Systems',
    status: 'Active',
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Brown',
    email: 'david.brown@example.com',
    phoneNumber: '555-2345',
    address: '321 Oak St, Hamletville, TX 67890',
    companyName: 'Innovate Corp.',
    status: 'Active',
  },
  {
    id: 7,
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@example.com',
    phoneNumber: '555-5678',
    address: '876 Maple St, Cityville, NY 12345',
    companyName: 'Widgets Inc.',
    status: 'Inactive',
  },
  {
    id: 8,
    firstName: 'Daniel',
    lastName: 'Taylor',
    email: 'daniel.taylor@example.com',
    phoneNumber: '555-8765',
    address: '543 Elm St, Townsville, CA 67890',
    companyName: 'Data Systems',
    status: 'Active',
  },
  {
    id: 9,
    firstName: 'Olivia',
    lastName: 'Anderson',
    email: 'olivia.anderson@example.com',
    phoneNumber: '555-2345',
    address: '987 Pine St, Villageton, TX 54321',
    companyName: 'Tech Solutions',
    status: 'Inactive',
  },
  {
    id: 10,
    firstName: 'Ryan',
    lastName: 'Davis',
    email: 'ryan.davis@example.com',
    phoneNumber: '555-7890',
    address: '654 Oak St, Cityville, NY 12345',
    companyName: 'Widgets Inc.',
    status: 'Active',
  },
  {
    id: 11,
    firstName: 'Ava',
    lastName: 'Garcia',
    email: 'ava.garcia@example.com',
    phoneNumber: '555-1234',
    address: '123 Main St, Villagetown, CA 12345',
    companyName: 'Tech',
    status: 'Active',
  },
  {
    id: 12,
    firstName: 'Christopher',
    lastName: 'Jones',
    email: 'christopher.jones@example.com',
    phoneNumber: '555-5678',
    address: '456 Oak St, Cityville, NY 67890',
    companyName: 'Widgets Inc.',
    status: 'Inactive',
  },
  {
    id: 13,
    firstName: 'Sophia',
    lastName: 'Martinez',
    email: 'sophia.martinez@example.com',
    phoneNumber: '555-8765',
    address: '789 Elm St, Hamletville, TX 54321',
    companyName: 'Data Systems',
    status: 'Active',
  },
  {
    id: 14,
    firstName: 'Matthew',
    lastName: 'Brown',
    email: 'matthew.brown@example.com',
    phoneNumber: '555-4321',
    address: '987 Birch St, Villagetown, CA 67890',
    companyName: 'Tech Solutions',
    status: 'Inactive',
  },
  {
    id: 15,
    firstName: 'Ella',
    lastName: 'Harris',
    email: 'ella.harris@example.com',
    phoneNumber: '555-7890',
    address: '654 Pine St, Townsville, NY 12345',
    companyName: 'Widgets Inc.',
    status: 'Active',
  },
  {
    id: 16,
    firstName: 'Noah',
    lastName: 'Clark',
    email: 'noah.clark@example.com',
    phoneNumber: '555-2345',
    address: '321 Oak St, Hamletville, TX 67890',
    companyName: 'Innovate Corp.',
    status: 'Active',
  },
];

export const debounce = (timeout = 10) => {
  let time = 0;
  return function (cb: any) {
    if (time) clearTimeout(time);
    time = window.setTimeout(() => {
      cb();
    }, timeout);
  };
};
