// ': 'Project 1',
//     'Client Name': '',
//     Action: 'email1@example.com',
//     Number: '555-1231',
//     City: '',
//     'Sale Person': '',
//     Estimator
export const RequestsHeadings = [
  "Project Name", "Client Name", "Number", "City",
  "Sale Person", "Estimator", "Status", "Action"
]

export const estimateRequests = [
  {
    ProjectName: 'Project 1',
    ClientName: 'Client A',
    Number: '555-1231',
    City: 'Cairo',
    SalePerson: 'Sales Rep 1',
    Estimator: 'Estimator 1',
    Status: 'active',
  },
  {
    ProjectName: 'Project 2',
    ClientName: 'Client B',
    Number: '555-1232',
    City: 'Paris',
    SalePerson: 'Sales Rep 2',
    Estimator: 'Estimator 2',
    Status: 'inactive',
  },
  {
    ProjectName: 'Project 3',
    ClientName: 'Client C',
    Number: '555-1233',
    City: 'New York',
    SalePerson: 'Sales Rep 3',
    Estimator: 'Estimator 3',
    Status: 'active',
  },
  {
    ProjectName: 'Project 4',
    ClientName: 'Client D',
    Number: '555-1234',
    City: 'Tokyo',
    SalePerson: 'Sales Rep 4',
    Estimator: 'Estimator 4',
    Status: 'inactive',
  },
  {
    ProjectName: 'Project 5',
    ClientName: 'Client E',
    Number: '555-1235',
    City: 'London',
    SalePerson: 'Sales Rep 5',
    Estimator: 'Estimator 5',
    Status: 'active',
  },
  {
    ProjectName: 'Project 6',
    ClientName: 'Client F',
    Number: '555-1236',
    City: 'Berlin',
    SalePerson: 'Sales Rep 6',
    Estimator: 'Estimator 6',
    Status: 'inactive',
  },
  {
    ProjectName: 'Project 7',
    ClientName: 'Client G',
    Number: '555-1237',
    City: 'Sydney',
    SalePerson: 'Sales Rep 7',
    Estimator: 'Estimator 7',
    Status: 'active',
  },
  {
    ProjectName: 'Project 8',
    ClientName: 'Client H',
    Number: '555-1238',
    City: 'Toronto',
    SalePerson: 'Sales Rep 8',
    Estimator: 'Estimator 8',
    Status: 'inactive',
  },
  {
    ProjectName: 'Project 9',
    ClientName: 'Client I',
    Number: '555-1239',
    City: 'Mumbai',
    SalePerson: 'Sales Rep 9',
    Estimator: 'Estimator 9',
    Status: 'active',
  },
  {
    ProjectName: 'Project 10',
    ClientName: 'Client J',
    Number: '555-1240',
    City: 'Seoul',
    SalePerson: 'Sales Rep 10',
    Estimator: 'Estimator 10',
    Status: 'inactive',
  },
];

