import { ScopeItem } from './type';

export const scopeItems: ScopeItem[] = [
  {
    id: '1',
    description: 'Design',
    orignalDuration: '12',
    start: new Date().toDateString(),
    finish: new Date().toDateString(),
    actualStart: new Date().toDateString(),
    actualFinish: new Date().toDateString(),
    remainingDuration: '12',
    scheduleCompleted: '12',
    totalFloat: '12',
    activityType: '12',
    predecessors: '12',
    successors: '12',
    activityCalendar: '12',
  },
  {
    id: '2',
    description: 'Design',
    orignalDuration: '12',
    start: new Date().toDateString(),
    finish: new Date().toDateString(),
    actualStart: new Date().toDateString(),
    actualFinish: new Date().toDateString(),
    remainingDuration: '12',
    scheduleCompleted: '12',
    totalFloat: '12',
    activityType: '12',
    predecessors: '12',
    successors: '12',
    activityCalendar: '12',
  },
  {
    id: '3',
    description: 'Design',
    orignalDuration: '12',
    start: new Date().toDateString(),
    finish: new Date().toDateString(),
    actualStart: new Date().toDateString(),
    actualFinish: new Date().toDateString(),
    remainingDuration: '12',
    scheduleCompleted: '12',
    totalFloat: '12',
    activityType: '12',
    predecessors: '12',
    successors: '12',
    activityCalendar: '12',
  },
  {
    id: '4',
    description: 'Design',
    orignalDuration: '12',
    start: new Date().toDateString(),
    finish: new Date().toDateString(),
    actualStart: new Date().toDateString(),
    actualFinish: new Date().toDateString(),
    remainingDuration: '12',
    scheduleCompleted: '12',
    totalFloat: '12',
    activityType: '12',
    predecessors: '12',
    successors: '12',
    activityCalendar: '12',
  },
];
